version: '3'
services: 
    wiki-qpuc:
        build: ./noplp/
        volumes:
            - ./noplp/:/usr/src/app/
        ports: 
            - 8085:8085
        environment: 
            PORT: 8085
            FLASK_DEBUG: 1